name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Upload frontend as artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend/out

  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Generate a stub embedded frontend
        run: |
          mkdir -p frontend/out
          touch frontend/out/.gitignore
          go generate ./...

      - name: Build backend
        run: go build

      - name: Upload backend as artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-admin-api
          path: static-admin

  build-all:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]
    steps:
      - uses: actions/checkout@v4

      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: frontend/out

      - name: Verify the frontend artifact
        run: |
          test -d frontend/out
          test -d frontend/out/_next
          test -f frontend/out/index.html

      - name: Generate the embedded frontend
        run: go generate ./...

      - name: Build binary
        run: go build

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-admin
          path: static-admin
